[licenses]
version = 2
confidence-threshold = 0.95
include-dev = false
include-build = true
unused-allowed-license = "allow"
allow = [
  "0BSD",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "BlueOak-1.0.0",
  "CC0-1.0",
  "CDLA-Permissive-2.0",
  "ISC",
  "MIT",
  "MIT-0",
  "OFL-1.1",
  "OpenSSL",
  "Unicode-3.0",
  "Unlicense",
  "Zlib",
]

[licenses.private]
ignore = false
